core/urls.py
from django.urls import path
from .views import guest_view,features,contact_page

urlpatterns = [
    path('home/',guest_view,name='guest-page'),
    path('features/',features,name='features'),
    path('contact-us/',contact_page,name='contact')

]

event_cnfig/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('users.urls')),
    path('',include('core.urls')),
    path('',include('event_app.urls')),
  
    
] + debug_toolbar_urls()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import sign_in,sign_up,activate_user,sign_out,create_group,assign_role,group_list,user_list,update_group,delete_group

app_name='users'
urlpatterns = [
    path("sign-out/",sign_out, name="sign-out"),
    path('activate/<int:id>/<str:token>/',activate_user),
    path('sign-in/',sign_in,name='sign-in'),
    path('sign-up/',sign_up,name='sign-up'),
    path('admin/create-group/',create_group,name='create-group'),
    path('admin/update-group/<int:group_id>/',update_group,name='update-group'),
    path('admin/delete-group/<int:group_id>/',delete_group,name='delete-group'),
    path('admin/<int:user_id>/assign-role',assign_role,name='assign-role'),
    path('admin/group-list',group_list,name='group-list'),
    path('admin/user-list',user_list,name='user-list'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User,Group,Permission
from django import forms
import re

class StyledFormMixin:
    """Mixin to apply style to form fields"""

    default_classes = "text-black border-2 border-gray-300 w-full p-3 rounded-lg shadow-sm focus:outline-none focus:border-green-500 focus:ring-rose-500"

    def apply_styled_widgets(self):
        for field_name, field in self.fields.items():

            # ----- TextInput -----
            if isinstance(field.widget, forms.TextInput):
                field.widget.attrs.update({
                    'class': self.default_classes,
                    'placeholder': f"Enter {field.label.lower()}"
                })

            # ----- Textarea -----
            elif isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({
                    'class': f"{self.default_classes} resize-none",
                    'placeholder': f"Enter {field.label.lower()}",
                    'rows': 5
                })

            # ----- SelectDateWidget -----
            elif isinstance(field.widget, forms.SelectDateWidget):
                field.widget.attrs.update({
                    "class": "border-2 border-gray-300 p-3 rounded-lg shadow-sm focus:outline-none focus:border-green-500 focus:ring-rose-500"
                })

            # ----- CheckboxSelectMultiple -----
            elif isinstance(field.widget, forms.CheckboxSelectMultiple):
                field.widget.attrs.update({
                    'class': "space-y-2"
                })

            # ----- Select -----
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs.update({
                    'class': "border-2 border-gray-300 p-3 rounded-lg shadow-sm focus:outline-none focus:border-green-500 focus:ring-rose-500 mt-3"
                })

            #  ----- Image / File Input -----
            elif isinstance(field.widget, forms.ClearableFileInput):
                field.widget.attrs.update({
                    'class': "block w-full text-sm text-gray-700 border-2 border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none focus:border-green-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-green-100 file:text-green-700 hover:file:bg-green-200",
                })

            # ----- Default case -----
            else:
                field.widget.attrs.update({
                    'class': self.default_classes
                })



class UserRegisterForm(StyledFormMixin,forms.ModelForm):
    password1=forms.CharField(widget=forms.PasswordInput(attrs={'id':'password'}),label='Passwod')
    confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={'id':'confirm_password'}),label='Confirm Password')
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password1','confirm_password']

        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'example@gmail.com' }),
            'password1':forms.PasswordInput(attrs={'placeholder': 'Password' }),
            'confirm_password':forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),
            }

    def clean_password1(self):
        password1=self.cleaned_data.get('password1')
        password2=self.cleaned_data.get('confirm_password')
        errors=[]
        if len(password1) < 8:
             errors.append('password must be 8 caracter')

        if (password1 and password2) and (password1!=password2):
            errors.append('password Ae Not same')

        if errors:
            raise forms.ValidationError(errors)
        
        return password1
    def clean_email(self):
        email=self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('ths email already exists')
        return email
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.apply_styled_widgets()
 
        
        
class AssignRoleForm(StyledFormMixin,forms.Form):
    role=forms.ModelChoiceField(queryset=Group.objects.all(),empty_label='Select a Role')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.apply_styled_widgets()





class CreateGroupForm(StyledFormMixin, forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(
    queryset=Permission.objects.all(),
    widget=forms.CheckboxSelectMultiple,
    required=False,
    label='Assign Permission'
    )

    class Meta:
        model = Group
        fields = ['name', 'permissions']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.apply_styled_widgets()


class AssignRole(StyledFormMixin,forms.Form):
    role=forms.ModelChoiceField(queryset=Group.objects.all(),empty_label='Select a Role')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.apply_styled_widgets()

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,Group
from .forms import UserRegisterForm,CreateGroupForm,AssignRole
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.decorators import login_required,user_passes_test, permission_required
from event_app.views import is_admin
from django.db.models import Prefetch

# Create your views here.
def sign_up(request):
    form=UserRegisterForm()
    if request.method=='POST':
        form=UserRegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            

            return redirect('users:sign-in')
            
    return render(request,'registation/sign-up.html',{'form':form})

def sign_in(request):
    if request.method=='POST':
        u=request.POST.get('username',None)
        p=request.POST.get('password',None)

        user=authenticate(request=request,username=u,password=p)
        if user:
            login(request,user)
            return redirect('guest-page')
        messages.error(request,'Invalid Username or Password')
    return render(request,'registation/sign-in.html')


def activate_user(request,id,token):
    try:
        user=User.objects.get(id=id)
        if default_token_generator.check_token(user,token):
            if not user.is_active:
                user.is_active=True
                user.save()
            return redirect('users:sign-in')
        else:
            return HttpResponse('Invalid User and Token')
        
    except Exception as e:
        return HttpResponse(f"invalid user ")
    
    
@login_required(login_url='users:sign-in')
def sign_out(request):
    logout(request)

    return redirect('users:sign-in')

@login_required(login_url='users:sign-in')   
@user_passes_test(is_admin,login_url='guest-page')
def create_group(request):
    form=CreateGroupForm()

    if request.method=='POST':
        form=CreateGroupForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,'Successfully group Created')
            return redirect('users:group-list')
    
    context={
        'forms':form,
        'role':'Admin',
        'page':'create-group'
    }
    return render(request,'group/create-group.html',context)

@login_required(login_url='users:sign-in')   
@user_passes_test(is_admin,login_url='guest-page')
def update_group(request,group_id):
    group=Group.objects.get(id=group_id)
    form=CreateGroupForm(instance=group)

    if request.method=='POST':
        form=CreateGroupForm(request.POST,instance=group)

        if form.is_valid():
            form.save()
            messages.success(request,f'Successfully {group.name} group Updated')
            return redirect('users:group-list')
    
    context={
        'forms':form,
        'role':'Admin',

    }
    return render(request,'group/create-group.html',context)


@login_required(login_url='users:sign-in')   
@user_passes_test(is_admin,login_url='guest-page')
def delete_group(request,group_id):
    try:
        group=Group.objects.get(id=group_id)
        group.delete()
        messages.success(request,f'Successfully  group Deleted')
    except Group.DoesNotExist as e:
        messages.error(request,f'This  {e}')

   
    return redirect('users:group-list')
    


@login_required(login_url='users:sign-in')   
@user_passes_test(is_admin,login_url='guest-page')
def assign_role(request,user_id):
    user=User.objects.get(id=user_id)
    form=AssignRole(initial={'role': user.groups.first()})
    if request.method=='POST':
        form=AssignRole(request.POST)
        if form.is_valid():
            
            group=form.cleaned_data
            user.groups.clear()
            user.groups.add(group['role'])
            messages.success(request,f'Successfully user:{user.first_name} role Assigned')
            return redirect('users:user-list')
        
    context={
        'forms':form,
        'role':'Admin'
    }
            
    return render(request,'group/assign-role.html',context)

@login_required(login_url='users:sign-in')   
@user_passes_test(is_admin,login_url='guest-page')
def group_list(request):
    groups=Group.objects.prefetch_related('permissions').all()

    context={
        'groups':groups,
        'role':'Admin',
        'page':'group-list'
    }
    return render(request,'group/group-list.html',context)

@login_required(login_url='users:sign-in')   
@user_passes_test(is_admin,login_url='guest-page')
def user_list(request):
    users=User.objects.prefetch_related('groups').all().order_by('-date_joined')


    context={
        'users':users,
        'role':'Admin',
        'page':'user-list'
    }
    return render(request,'user/user-list.html',context)

users/templates/group/assign-role.html
{% extends "guest/guest-page.html" %}
{% block title %}Assign Role{% endblock title %} 
{% block main_class %}class="flex-grow flex items-center justify-center px-6 py-10 min-h-lvh"{% endblock main_class %}
{% block content  %}


<div class="mx-auto my-28 bg-gray-800  shadow-lg rounded-2xl p-8 w-full max-w-2xl transition duration-300">
    <h2 class="text-2xl font-semibold text-center text-gray-800  mb-6">Create Group</h2>

        <!-- Messages -->
    {% if messages %}
        <div class="mb-4">
            {% for message in messages %}
                <div class="p-2 text-center font-semibold 
                            {% if message.tags == 'success' %}text-green-600{% else %}text-red-600{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <form method="POST" class="space-y-6 mb-8">
        {% csrf_token %}

        
        <div class="text-gray-800 flex flex-col w-full">
            {{form.role.label}}
            {{ forms.role }}
        </div>


       <div class="text-center mt-8 mb-6 flex justify-center">
        <button 
            type="submit" 
            class="w-1/2 h-11 bg-gradient-to-r from-indigo-600 to-blue-500 text-white font-semibold 
                rounded-lg shadow-md hover:shadow-lg hover:scale-[1.02] 
                focus:outline-none focus:ring-4 focus:ring-blue-300 
                transition-all duration-300 ease-in-out"
        >
            Submit
        </button>
        </div>



    </form>
</div>

{% endblock content  %}

users/templates/group/create-group.html
{% extends "guest/guest-page.html" %}
{% block title %}Create Group{% endblock title %} 
{% block main_class %}class="flex-grow flex items-center justify-center px-6 py-10 min-h-lvh"{% endblock main_class %}
{% block content  %}


<div class="mx-auto my-28 bg-gray-800  shadow-lg rounded-2xl p-8 w-full max-w-2xl transition duration-300">
    <h2 class="text-2xl font-semibold text-center text-gray-800  mb-6">Create Group</h2>

        <!-- Messages -->
    {% if messages %}
        <div class="mb-4">
            {% for message in messages %}
                <div class="p-2 text-center font-semibold 
                            {% if message.tags == 'success' %}text-green-600{% else %}text-red-600{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <form method="POST" class="space-y-6 mb-8">
        {% csrf_token %}

        
        <div>
            {{ forms.name }}
        </div>
        <div class="font-bold text-gray-400 ">{{forms.permissions.label}}:</div>
        <div class="font-bold text-md text-gray-300 ">{{forms.permissions}}</div>
        {% comment %} <div class="h-32 overflow-y-scroll text-black border-2 border-gray-300 w-full p-3 rounded-lg shadow-sm focus:outline-none focus:border-green-500 focus:ring-rose-500">
            {{forms.permissions}}
        </div>
      {% endcomment %}


        <!-- Submit Button -->
       <div class="text-center mt-8 mb-6 flex justify-center">
        <button 
            type="submit" 
            class="w-1/2 h-11 bg-gradient-to-r from-indigo-600 to-blue-500 text-white font-semibold 
                rounded-lg shadow-md hover:shadow-lg hover:scale-[1.02] 
                focus:outline-none focus:ring-4 focus:ring-blue-300 
                transition-all duration-300 ease-in-out"
        >
            Submit
        </button>
        </div>



    </form>
</div>

{% endblock content  %}

users/templates/group/group-list.html
{% extends "guest/guest-page.html" %}
{% block title %}Groups and Permissions{% endblock title %} 
{% block main_class %}class="mt-24 mb-20 min-h-lvh"{% endblock main_class %}
{% block content %}
    <h2 class="text-2xl font-bold mb-4 text-center">Groups and Permissions</h2>
    <div class="overflow-x-auto">
        <table class="table-auto w-full border-collapse border border-gray-300">
          <thead>
            <tr class="bg-gray-100">
              <th class="border border-gray-300 px-4 py-2">Group Name</th>
              <th class="border border-gray-300 px-4 py-2">Permissions</th>
              <th class="border border-gray-300 px-4 py-2">Update/Delete - Permissions</th>
            </tr>
          </thead>
          <tbody>
            <!-- Example group data -->

            {% for group in groups %}
            <tr class="odd:bg-white even:bg-gray-50">
              <td class="border border-gray-300 px-4 py-2 font-medium">
                {{group.name}}
              </td>
              <td class="border border-gray-300 px-4 py-2">
                <ul class="list-disc list-inside">
                  {% for permission in group.permissions.all %}
                  <li>{{permission.name}} || {{permission.codename}}</li>
                  
                  {% empty %}
                  <li>No Permissions</li>
                  {% endfor %}
                </ul>
              </td>
              <td class="border border-gray-300 px-4 py-2 font-medium">
                <a href="{% url 'users:update-group' group.id %}" class="text-green-400 hover:text-green-500">Update</a>
                <span> / </span>
                <a href="{% url 'users:delete-group' group.id %}" class="text-red-400 hover:text-red-500">Delete</a>
              </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>
      </div>
{% endblock content %}